### ISSUE TITLE
[Docker] Error introduced with latest commit

### ISSUE THREAD

**Issue by Trigus42** [Malexion/Rhythm-Bot#71]
I use Docker and build the image myself. Since the latest commit (https://github.com/Malexion/Rhythm-Bot/commit/29a3dcc7d9d6e2128bff9337cff036a24ad50f9e) I get the following error:

```
> rhythm-bot@2.1.5 start:prod /home/rhythmbot
> NODE_ENV=production node --trace-warnings dist/app

[Error: SQLITE_CANTOPEN: unable to open database file] {
errno: 14,
code: 'SQLITE_CANTOPEN'
}
```
If if checkout the previous commit everything works.

I cloned the repo into the `src` subfolder. This is my compose file:
```yaml
version: '3'

services:
  rhythm-bot-server:
    container_name: rhythm-bot
    build:
      context: './src'
      dockerfile: './Containerfile'
    environment:
      DISCORD_TOKEN: '(redacted)'
```
